### PR TITLE
Changed Header to NavBar. Style changes applied - MariaD 12.20.24

### PR DESCRIPTION
**Pull request by tobemari**
- Header component name changed to NavBar
- Minor tweaks to styling, including adjustments for margin and padding in key sections, to align with the fixed positioning

### CODE REVIEW

**Review by nihalerdal — APPROVED** [review]
Looks good Maria, approved! I have a suggestion: how about adding some space between the events and the Navbar?

**Review by StuvaScript — APPROVED** [review]
Looks great Maria! I agree with Nihal about maybe matching the padding height with the padding under the testimonials. Other than that, great job!

**Comment by tobemari** [comment]
> Looks good Maria, approved! I have a suggestion: how about adding some space between the events and the Navbar?

Good idea, thank you Nihal! I have made the event grid for the event cards and I think you can check that changes in my next PR

**Comment by tobemari** [comment]
> Looks great Maria! I agree with Nihal about maybe matching the padding height with the padding under the testimonials. Other than that, great job!

Thank you Stu! I've done the event grid and you can check it in my next PR

**Pull request merged**
